module.exports =[{
    name: '', 
    price: 00, 
    image: '', 
    description: '',
    id: 0},{
    name: '',
    price: 00, 
    image: '', 
    description: '',
    id: 1},{
    name: '', 
    price: 00,
    image: '',
    description: '',
    id: 2},{ 
    name: '', 
    price: 00, 
    image: '',
    description: '',
    id: 3},{
    name: '', 
    price: 00, 
    image: '', 
    description: '',
    id: 4},{
    name: '', 
    price: 00, 
    image: '', 
    description: '',
    id: 5
     }]
